const HOT_RECOMMEND_LIST = "HOT_RECOMMEND_LIST";
const GET_TOUR_DATA = "GET_TOUR_DATA";
const GET_SLIDE_CLASSIFY_DATA = "GET_SLIDE_CLASSIFY_DATA";
const GET_FLOOR_LIST = "GET_FLOOR_LIST";



export {
    HOT_RECOMMEND_LIST,
    GET_TOUR_DATA,
    GET_SLIDE_CLASSIFY_DATA,
    GET_FLOOR_LIST
}